[package]
name = "pithos-native-codec-v14"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pithos-core = { path = "../pithos-core" }
pithos-analysis = { path = "../pithos-analysis" }
pithos-codecs = { path = "../pithos-codecs" }
pithos-native-v13 = { package = "pithos-native-codec-v13", path = "../pithos-native-codec-v13" }
blake3.workspace = true
