[package]
name = "pithos-testkit"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pithos-core = { path = "../pithos-core" }
pithos-engine = { package = "pithos-engine-next", path = "../pithos-engine-next" }
pithos-format = { path = "../pithos-format" }
blake3.workspace = true
crc32c.workspace = true
tempfile.workspace = true
proptest.workspace = true
same-file.workspace = true
