[package]
name = "pithos-native-codec-v12"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pithos-core = { path = "../pithos-core" }
pithos-analysis = { path = "../pithos-analysis" }
pithos-codecs = { path = "../pithos-codecs" }
pithos-native-v11 = { package = "pithos-native-codec-v11", path = "../pithos-native-codec-v11" }
blake3.workspace = true
