[package]
name = "pithos-representation-profiler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pithos-native-v12 = { package = "pithos-native-codec-v12", path = "../pithos-native-codec-v12" }
pithos-native-v14 = { package = "pithos-native-codec-v14", path = "../pithos-native-codec-v14" }
pithos-native-v15 = { package = "pithos-native-codec-v15", path = "../pithos-native-codec-v15" }
pithos-native-v16 = { package = "pithos-native-codec-v16", path = "../pithos-native-codec-v16" }
pithos-native-v17 = { package = "pithos-native-codec-v17", path = "../pithos-native-codec-v17" }
pithos-native-v18 = { package = "pithos-native-codec-v18", path = "../pithos-native-codec-v18" }
