[package]
name = "pithos-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pithos-core = { path = "../pithos-core" }
pithos-format = { path = "../pithos-format" }
pithos-io = { path = "../pithos-io" }
pithos-codecs = { path = "../pithos-codecs" }
pithos-planner = { path = "../pithos-planner" }
rayon.workspace = true
crossbeam-channel.workspace = true
tracing.workspace = true
blake3.workspace = true
crc32c.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
same-file.workspace = true
